#!/usr/bin/dh-exec
usr/include/*/qt6/QtCore/6.*/*
usr/include/*/qt6/QtDBus/6.*/*
usr/include/*/qt6/QtDeviceDiscoverySupport/6.*/*
usr/include/*/qt6/QtEglFSDeviceIntegration/6.*/*
[linux-any] usr/include/*/qt6/QtEglFsKmsGbmSupport/6.*/*
[linux-any] usr/include/*/qt6/QtEglFsKmsSupport/6.*/*
usr/include/*/qt6/QtFbSupport/6.*/*
usr/include/*/qt6/QtGui/6.*/*
usr/include/*/qt6/QtInputSupport/6.*/*
[linux-any] usr/include/*/qt6/QtKmsSupport/6.*/*
usr/include/*/qt6/QtNetwork/6.*/*
usr/include/*/qt6/QtOpenGL/6.*/*
usr/include/*/qt6/QtPrintSupport/6.*/*
usr/include/*/qt6/QtSql/6.*/*
usr/include/*/qt6/QtTest/6.*/*
usr/include/*/qt6/QtWidgets/6.*/*
usr/include/*/qt6/QtXml/6.*/*
