#!/usr/bin/dh-exec
usr/lib/*/libQt6EglFSDeviceIntegration.so.*
[linux-any] usr/lib/*/libQt6EglFsKmsGbmSupport.so.*
[linux-any] usr/lib/*/libQt6EglFsKmsSupport.so.*
usr/lib/*/libQt6XcbQpa.so.*
usr/lib/*/qt6/plugins/egldeviceintegrations/libqeglfs-emu-integration.so
[linux-any] usr/lib/*/qt6/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so
[linux-any] usr/lib/*/qt6/plugins/egldeviceintegrations/libqeglfs-kms-integration.so
usr/lib/*/qt6/plugins/egldeviceintegrations/libqeglfs-x11-integration.so
[linux-any] usr/lib/*/qt6/plugins/generic/libqevdevkeyboardplugin.so
[linux-any] usr/lib/*/qt6/plugins/generic/libqevdevmouseplugin.so
[linux-any] usr/lib/*/qt6/plugins/generic/libqevdevtabletplugin.so
[linux-any] usr/lib/*/qt6/plugins/generic/libqevdevtouchplugin.so
[linux-any] usr/lib/*/qt6/plugins/generic/libqlibinputplugin.so
usr/lib/*/qt6/plugins/generic/libqtslibplugin.so
usr/lib/*/qt6/plugins/generic/libqtuiotouchplugin.so
usr/lib/*/qt6/plugins/imageformats/libqgif.so
usr/lib/*/qt6/plugins/imageformats/libqico.so
usr/lib/*/qt6/plugins/imageformats/libqjpeg.so
usr/lib/*/qt6/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
usr/lib/*/qt6/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
usr/lib/*/qt6/plugins/platforms/libqeglfs.so
[linux-any] usr/lib/*/qt6/plugins/platforms/libqlinuxfb.so
usr/lib/*/qt6/plugins/platforms/libqminimal.so
usr/lib/*/qt6/plugins/platforms/libqminimalegl.so
usr/lib/*/qt6/plugins/platforms/libqoffscreen.so
usr/lib/*/qt6/plugins/platforms/libqvnc.so
usr/lib/*/qt6/plugins/platforms/libqxcb.so
usr/lib/*/qt6/plugins/xcbglintegrations/libqxcb-glx-integration.so
[linux-any] usr/lib/*/qt6/plugins/platforms/libqvkkhrdisplay.so
usr/lib/*/qt6/plugins/tls/libqcertonlybackend.so
usr/lib/*/qt6/plugins/tls/libqopensslbackend.so
usr/lib/*/qt6/plugins/xcbglintegrations/libqxcb-egl-integration.so
